### ISSUE TITLE
Using RESTe to consume multiple REST services

### ISSUE THREAD

**Issue by jvandijk** [jasonkneen/RESTe#12]
Hey @jasonkneen,

This library works awesome. Thanks for creating it! We've recently build a Parse module https://github.com/Sensimity/com.sensimity.ti.parse which depends on RESTe for it's communication to the Parse REST api. 

While creating another module though, that also uses RESTe we run into in an issue, that the 2nd loaded module, also depending on RESTe alters the api.config which brakes the URL configuration of the  1st loaded module.

Can we somehow work around this issue?

**Comment by jasonkneen** [comment]
Yep - I have a workaround to post up in the next day or so that will change the instantiation to use _new_ when creating a new rest instance and this will solve it.

**Comment by jvandijk** [comment]
Damn you are fast! :smile: Looking forward to the update!

**Comment by jasonkneen** [comment]
Merged into master and updated readme - should work fine. I've been using it for a few weeks in a project that has two configs -- one for the client API and one for Parse ;)

**Comment by jasonkneen** [comment]
btw, if you know a way to make reste.js work with new operator and without I'm happy to review a PR on it - I tried but ran out of time!
