### ISSUE TITLE
Model & Alloy

### ISSUE THREAD

**Issue by pakoArtal** [jasonkneen/RESTe#15]
Hi Jason,

Thank you for your code. Is really useful!

Following your location example I'm trying to show a model with Alloy:

locationDetail.js

```
var args = arguments[0] || {};

Alloy.Models.location.fetch({
   link: args.modelId
});
```

locationDetail.xml

```
<Alloy>
<Window id="locationDetailWindow"  model="location">
<Label class="title" text="{name}"/>
<Label class="link" text="{address}"/>
    </Window>
</Alloy>
```

But I'm getting this error:

[ERROR] :  TiExceptionHandler: (main) [358673,425480] ----- Titanium Javascript Runtime Error -----
[ERROR] :  TiExceptionHandler: (main) [0,425480] - In alloy/controllers/locationDetail.js:153,25
[ERROR] :  TiExceptionHandler: (main) [0,425480] - Message: Uncaught TypeError: Cannot call method 'on' of undefined
[ERROR] :  TiExceptionHandler: (main) [0,425480] - Source:     Alloy.Models.location.on("fetch change destroy", __alloyId14);
[ERROR] :  V8Exception: Exception occurred at alloy/controllers/locationDetail.js:153: Uncaught TypeError: Cannot call method 'on' of undefined

line 153 is:
Alloy.Models.location.on("fetch change destroy", __alloyId14);

Can you help me,please?

**Comment by jasonkneen** [comment]
Don't use model attribute within the window -- it's not supported.

To fetch a model use

``` javascript
Alloy.Collections.locations.fetch()
```

of that's the name of your collection

If you want to pass a model to a controller / view, pass it to a "$model" argument when creating the controller

Please see the readme.

**Comment by frodfigu** [comment]
Nice work. But I have a related question.

I have some like this config

`{
        name: "publicacion",
        id: "objectId",
        read: "getPublicacionDetalle",
        content:"result",
        collections: [{
            name: "publicaciones",
            content: "result",
            read: "getPublicacionesCentroClasesByUser"
        }]
    }`

So.. How Can I fetch only a single model? I want to get a model that this isn´t in the collection. When the user get into a push notification for example. How can I do this without get the entire collection?

Thank you very much.

**Comment by jasonkneen** [comment]
To get a single model, you need to have a method in place that can get by ID and have that assigned to the "read" property of the model. Then you just do:

```
var model = reste.createModel("video", {id: THE_ID_YOU_WANT});
model.fetch();
```

The model is then populated. You'll need to ensure you have a read property against the model definition that points to a method that accepts an ID and calls an endpoint that can filter by ID.
