### ISSUE TITLE
Nice work, but how can i fetch related objects?

### ISSUE THREAD

**Issue by boardmain** [jasonkneen/RESTe#16]
how can i fetch related objects?

**Comment by jasonkneen** [comment]
What do you mean by related? Context?

**Comment by boardmain** [comment]
i created a class in parse.com with related class column and im tring to fetch it from titanium and i see like:

```

{"contatore":5,"createdAt":"2015-12-02T19:34:12.546Z","nome":"Furgone2","objectId":"SrTmYGyRRT","registrazioni":{"__type":"Relation","className":"registrazioni"},"targa":"DJ464JK","updatedAt":"2015-12-02T21:22:16.674Z"}
```

registrazioni is another object

**Comment by jasonkneen** [comment]
Check the parse.com docs -- and use the config to create a template endpoint e.g:

`{
        name: "roomTests",
        get: 'classes/tests/?where={"$relatedTo":{"key":"tests","object":{"__type":"Pointer","objectId":"<roomId>","className":"rooms"}}}',
        expects: ["roomId"]
    }`

in this example it's getting from a class/collection called "tests" and is doing a related lookup.
