### ISSUE TITLE
Ovewrite requestHeaders

### ISSUE THREAD

**Issue by buje** [jasonkneen/RESTe#19]
Then we define requestHeaders in config object like this : 
`requestHeaders: {
    "Content-Type": "application/json"
},`

if we want overwrite the requestHeaders for a specific route like this : 
`{
  name : 'reportCheckin',
  post : 'checkins/<checkin_id>/reports',
  headers: {
      "Content-Type": "application/x-www-form-urlencoded"
  }
},`

this didn't work.

I found the solution by switching non-global header in top of global request headers : 

`// non-global headers if (args.headers) {
    for (var header in args.headers) {
// load up any request headers
        if (header == "Content-Type" && args.headers[header] == "application/x-www-form-urlencoded") {
            formEncode = true;
        } else if (header == "Content-Type" && args.headers[header] == "application/json") {
            formEncode = false;
        } else {
            formEncode = true;
        }
        http.setRequestHeader(header, typeof args.headers[header] == "function" ? args.headers[header]() : args.headers[header]);
    }
}`

`// load up any global request headers requestHeaders.forEach(function(header) {
    if (header.name == "Content-Type" && header.value == "application/x-www-form-urlencoded") {
        formEncode = true;
    }
    http.setRequestHeader(header.name, typeof header.value == "function" ? header.value : header.value);
});`

**Comment by jasonkneen** [comment]
Odd. I'm pretty sure I had that working. Would you mind doing a PR with this update so i see what's changed?

**Comment by buje** [comment]
I don't know how to create a PR, i must create a new branch ?

I attach the file to my comment. (juste invert the block line 77 to 84 with the block line 86 to 101)

[reste.js.txt](https://github.com/jasonkneen/RESTe/files/129039/reste.js.txt)

**Comment by jasonkneen** [comment]
Great way to learn. 
1. Fork the repo
2. Edit the file and replace with your version and describe your changes
3. Create a PR (which will auto select your changes) and submit. 

;)

**Comment by m1ga** [comment]
Is this already in the latest RESTe?
I have a SessionKey in my requestHeaders but it will change once I login, so I need to change that in my later requests. If I set my 
`api.config({requestHeaders: "SessionKey":Ti.App.Properties.getString("sessionkey")})`
in alloy.js but its changing it when I call my apis later on.

**Comment by jasonkneen** [comment]
you can specify request headers for each method call -- if that helps -- but I'll also look at adapting the ```

`beforePost: function(params, callback) {
        params.apiKey = getApiKey();
        callback(params);
    }`

event against the global config to pass in the headers too -- that way you could change the headers for each call and in one place.

UPDATE: checked the code and you CAN specify a function as a header for the method based headers -- but it's not executing it correctly for the global one -- will issue a fix

**Comment by m1ga** [comment]
Nice, thanks! I saw that reste.setRequestHeaders() will clear the existing one. Perhaps a changeRequestHeader("key":"value")  would be a good addition (that will change or add if not existing). I'll make a pull request later if you don't mind
