### ISSUE TITLE
Dynamic headers such as token

### ISSUE THREAD

**Issue by annakozy2011** [jasonkneen/RESTe#20]
Please, add a callback for dynamic headers, such as Token. 
Or is it already there?

**Comment by jasonkneen** [comment]
Please explain what you mean and give an example

**Comment by annakozy2011** [comment]
I have a number of APIs, where I have to send Token in the header. For that purpose, I modify reste.js, adding to it something of this sort after setting other headers and before actually making a request (in makeHttpRequest)

var token = Ti.App.Properties.getString("x-token","")
        if (token != "")
        {
            http.setRequestHeader("X-Token",token);
        } 

I thought it would be good to have something like "getHeaders()" dynamic callback, in addition to static headers that you already provide, because headers may vary depending on the lifecycle of the app  (logged in, not logged in) and sometimes request.

It is not possible to set this dynamic header at the point of instantiating Reste, because there can be no token (user is not logged in), besides - tokens change from time to time.

**Comment by annakozy2011** [comment]
Ah, I just found it. Header can be a function, right? Ok.

**Comment by annakozy2011** [comment]
Ok, I had to reopen it, because I found a bug with this (small, but critical). It's this line, and it is missing FUNCTION CALL (a couple of parenthesis after the first case of header.value, that is, if it's a function).

 http.setRequestHeader(header.name, typeof header.value == "function" ? header.value : header.value);

**Comment by jasonkneen** [comment]
In not sure what the issue is here. The headers code accepts properties or
a function to dynamically set. If you have a PR to submit please do.

**Comment by annakozy2011** [comment]
Yeah, there is already pull request for that from someone else (I fixed locally, checked, it works): 

https://github.com/jasonkneen/RESTe/pull/11

**Comment by jasonkneen** [comment]
Yep. Has conflicts. Needs resolving.
