### ISSUE TITLE
Display Image returned from REST

### ISSUE THREAD

**Issue by adamtarmstrong** [jasonkneen/RESTe#22]
Connecting to MapQuest StaticMap API.
- Using xhr, this simply works to assign returned jpeg to ImageView
     $.wedRouteMap.image = this.responseData;
- I tried to accomplish the same through reste this way and it doesn't work.  Am I doing something wrong?

apiMapquestRouteMap.getMap({
        queryString: ............(removed to simplify)......
            }, function(mapObject) {
                $.wedRouteMap.image = mapObject.responseData;
            });

Ti.API.info(mapObject) returns a bunch of gibberish.

----excerpt....not the entire contents----
ÿØÿàJFIFÿÛCÿÛCÿÀ"ÿÄ 
ÿÄµ}!1AQa"q2¡#B±ÁRÑð$3br  
%&'()_456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz¢£¤¥¦§¨©ª²³´µ¶·¸¹ºÂÃÄÅÆÇÈÉÊÒÓÔÕÖ×ØÙÚáâãäåæçèéêñòóôõö÷øùúÿÄ 
ÿÄµw!1AQaq"2B¡±Á #3RðbrÑ
$4á%ñ&'()_56789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz¢£¤¥¦§¨©ª²³´µ¶·¸¹ºÂÃÄÅÆÇÈÉÊÒÓÔÕÖ×ØÙÚâãäåæçèéêòóôõö÷øùúÿÚ?þ <M©þÕ?jÿ_~üCý>xCáìÛû+üzÕu³Æ¯¾-ño>3|pý²ümieyðóöÓý´oxÁ:oì·áëÅº­ï5¯µjVÖÅa? Ú~Î_ðQ»xmmk/Ø;{xc·#ÿçý¨¥  ,Z$ÌßðW)1,¥Ë6âNrs^§x{ö§ñüöoÙ§ãÀ?F×þ  ÿÿü>5_³OÄOÚ"Mí´çü_þ¿øFá_þÖ?²øðÒñÖÎ­ÿ   Ïü$?ÚZA±ÿdè¿ð}aÿ
## .........

and I tried to do this to assign to the ImageView (like in the xhr sample above)
       $.wedRouteMap.image = mapObject.responseData;
but no image is shown.

**Comment by jasonkneen** [comment]
are you base64decoding the image?
