### ISSUE TITLE
Getting Model Data from Tableview Click

### ISSUE THREAD

**Issue by cansoysal** [jasonkneen/RESTe#38]
Hi @jasonkneen,
How can I get model data from tableview click? I tried e.rowdata, e.model but all came undefined.
Many thanks for this incredible library.

**Comment by jasonkneen** [comment]
You have to use the index to get the model back from the collection so

`var model = Alloy.Collections.name.at(e.index)`

**Comment by cansoysal** [comment]
Oh, great, thank you 👍
