### ISSUE TITLE
Helper Function for Request Headers

### ISSUE THREAD

**Issue by adamtarmstrong** [jasonkneen/RESTe#39]
In your doc I see you have a helper function to "setUrl".  
api.setUrl("http://whatever");

Is there a similar helper function to override/set the Request Headers?

**Comment by jasonkneen** [comment]
What's your use case?

You can send new request headers on every method -- so there shouldn't be the need to do it on the fly AFAIK

**Comment by adamtarmstrong** [comment]
Maybe it is more of an issue with my config then.

my config currently has.
`
Alloy.Globals.api.config({
    debug: true,
    autoValidateParams: false,
    validatesSecureCertificate: false,
    timeout: 32000,
    url: "URL HERE",
    requestHeaders: {
        "User": Ti.App.Properties.getString('myEmail'),
        "Authorization": Titanium.Utils.sha1(Ti.App.Properties.getString('myEmail') + 'SALT_HERE' + Ti.App.Properties.getString('myTitle'))
    },
    models: [{
        name: "name",
        id: "id",
        collections: [{
            name: "myTopRetMkts",
        .....
`

It appears that it is pulling the saved Properties on startup which would be from pervious login.  If user logs in as a different user (ex. impersonation) then the request headers are loading on startup and not using the newly saved Properties.  Instead of passing Request Headers on every API endpoint (about 20) it'd be nice to switch out that request headers once on the fly and thereby apply to all future request for the session.

**Comment by jasonkneen** [comment]
Yeh -- that's normal -- config is loaded once and that's it so basically if you wanted to change a value and have it use it you simply put a function in place -- here's one I have that used parse and session token that could change after the config was created:

```Alloy.Globals.reste.config({
    timeout: 20000,
    debug: true,
    autoValidateParams: false,
    url: Alloy.CFG.useDevUrl === true? Alloy.CFG.devUrl : Alloy.CFG.baseUrl,
    requestHeaders: {
        "X-Parse-Application-Id": "XXXXX",
        "X-Parse-REST-API-Key": "YYYY",
        "Content-Type": "application/json",
        "X-Parse-Session-Token": getSessionToken()
    },

etc ```

the getSessionToken() function would get the token and so would be called each time by RESTe

So basically RESTe will check the value of the header and if it's a function it calls it -- so just return your property at that point.

**Comment by adamtarmstrong** [comment]
Perfect!  Thanks!
