### ISSUE TITLE
Does RESTe support "reset: false" to use in Lazy Loading?

### ISSUE THREAD

**Issue by adamtarmstrong** [jasonkneen/RESTe#40]
I am trying to implement Lazy Loading on a Search TableView and trying to figure out how to add results to the Collection without 'resetting'.  My research of backbone.js lead me to the conclusion that I need to be passing 'reset: false' while using 'fetch'.

I tried the following, but can't seem to get it to work.
`
Alloy.Collections.peopleSearch.fetch({
		searchText: encodeURI($.search.value),
		myContact: peopleMyContact
		page: 1
	}, { reset: false });
`

**Comment by jasonkneen** [comment]
Don't believe so -- will need to test and do some work on that

**Comment by jasonkneen** [comment]
Without refreshing the list? 

silent: true should do that.
