### ISSUE TITLE
Add abort method

### ISSUE THREAD

**Issue by m1ga** [jasonkneen/RESTe#42]
For a recent project I needed an abort method:
```
reste.abort = function() {
            http.abort();
    }
```

for this http has to be accessible outside `makeHttpRequest`
Would this be a good change/addition? In my case I declared `var http` in line 5 but that might bring some memory increase

**Comment by m1ga** [comment]
Ok, a global `var http` makes problems when you use the api in different classes. But still a `abort` function would be nice to have

**Comment by jasonkneen** [comment]
agreed -- will look at this
