### ISSUE TITLE
FormData Usage?

### ISSUE THREAD

**Issue by adamtarmstrong** [jasonkneen/RESTe#43]
I have used RESTe on numerous occasions now and in every instance my APIs were simple, text, objects, properties, etc...

I am now trying to use with a vendor to upload photos and as such their API requires I submit as Form Data.

my RESTE config looks like this:
`
Alloy.Globals.texas.config({
    debug: true,
    autoValidateParams: false,
    validatesSecureCertificate: false, 
    timeout: 30000,
    url: 'REMOVED',
    requestHeaders: {
    	"Content-Type": "multipart/form-data",
    	"Authorization": 'REMOVED"
    },
    methods: [{
        name: "postInsuredClaimMultiFileUpload",
        post: "multiFileUpload",
`

and I am executing like this:
`
			var bodyParams = {
				policy_number: args.pol,
				loss_sequence: args.seq,
				claimant_sequence: args.clmn,
				assigned_to: "CLAIMS",
				//file_1: fileOneEncoded,
				//file_2: fileTwoEncoded,
				//file_3: fileThreeEncoded,
				description: encodeURI("VEHICLE PHOTOS - MOBILE"),
				mark_as_processed: 'N'
			};
			Alloy.Globals.texas.postInsuredClaimMultiFileUpload({
					body: bodyParams
				}, function(apiResponse) {
					alert("Response received:\n" + JSON.stringify(apiResponse));
			});
`

But it continues to fail.  I can get it to work in Postman just fine so obviously I am doing something wrong.  Is there something special I need to do to submit as From Data?

**Comment by frodfigu** [comment]
I have the same problem.
