### ISSUE TITLE
Ability to indicate a parent item to begin collection data from

### ISSUE THREAD

**Issue by raybelisle** [jasonkneen/RESTe#46]
ArrowDB (and other REST API's) sometimes return their results in nested objects. Currently RESTe allows you to configure a top level object as it's collection configuration. Would be nice if you could provide a JSON object path as the collection configuration. ie. response.object.cars

**Comment by jasonkneen** [comment]
Thanks -- working on this one

**Comment by adamtarmstrong** [comment]
FWIW, I found a way around this.
in the onLoad event I added a transform:
```
 onLoad: function(e, callback) {
	var transform = e.response;
        callback(transform);
    }
```
This moves the entire "response" object into the parent making "posts" now accessible from the parent.
```
 collections: [{
            name: "queryPosts",
            content: "posts",
            read: "getQueryPosts"
        }],
```

**Comment by jasonkneen** [comment]
Awesome.
