### ISSUE TITLE
Add support for additional URL parameters

### ISSUE THREAD

**Issue by brentonhouse** [jasonkneen/RESTe#5]
Would be nice to be able to set additional URL parameters such those required for ACS (key and _session_id).

**Comment by jasonkneen** [comment]
you can do this already - using <tokenID> or <sessionId> notation in the URLs called.

**Comment by brentonhouse** [comment]
Something like this?
Url: https://api.cloud.appcelerator.com/v1/users/show/me.json?key=myapikey&_session_id=mysessionid

where  `users/show/me.json` is the method and the parameters are part of the base url

**Comment by jasonkneen** [comment]
already there - please see the readme

```
{
        name: "getVideoById",
        get: "classes/videos/<videoId>"
}, 
```
