### ISSUE TITLE
Adding data to data object sent to the server before send

### ISSUE THREAD

**Issue by developer82** [jasonkneen/RESTe#55]
I'm wondering if there is a way to add data to the data object (json) that's being sent to the server by RESTe just before it's sent to the server, for some of the methods.

I have device information that I need to send with some of the calls, so instead of attaching that information everywhere in my code when making the call, can RESTe recognize a command as a command that needs to add this data to and attach it to the data being sent to the server just before it dispatches the request?

(hope my question was clear :) )

**Comment by jasonkneen** [comment]
lookup the "beforeSend" event in the readme. There should also be a beforeUpdate, beforeSave, beforeInsert.

**Comment by developer82** [comment]
Thanks. But beforeSend is generic. The extra data I want to add is only for some of the methods - can in be done on a method level, or get the executing method name?
