### ISSUE TITLE
Example of Models/collections

### ISSUE THREAD

**Issue by nuno** [jasonkneen/RESTe#6]
Hey @jasonkneen It was nice if you could provide an example for Models/collections.

I have the module fully working, but now I want test the Models/collections.
This make sense to you?

index.js

```
api.config({
    debug : true, // allows logging to console of ::REST:: messages
    autoValidateParams : false, // set to true to throw errors if <param> url properties are not passed
    timeout : 4000,
    url : "https://api.dribbble.com/v1/",
    requestHeaders : {
        "Authorization" : "Bearer eifwqifewpfoiweoifoiwefioqwe",
        "Content-Type" : "application/json"
    },
    models : [{
        name : "shots",
        id : "objectId",
        collections : [{
            name : "shots",
            content : "results",
            read : "getShots"
        }],
    }],
    methods : [{
        name : "getShots",
        get : "shots"
    }],
    onError : function(e) {
        alert("There was an error accessing the API");
        console.log("Error accessing the API: ", e);
    },
}); 

```

Thanks.
Love this module library :)

**Comment by jasonkneen** [comment]
Sorry missed this - did you get this working?

**Comment by nuno** [comment]
Hey Jason  np, I haven't time yet to test (But I want try ), but if you could give a example I will appreciate it jason kneen :)
Some alloy example perhaps

**Comment by jasonkneen** [comment]
So your config above looks right - in your alloy code you simply have to reference the collections so here's an example from an app I'm working on:

``` xml
<TableView onClick="selectNews" dataCollection="news" dataTransform="renderItem">
        <TableViewRow height="152">
            <ImageView height="Ti.UI.SIZE" image="{image}" />
             <View class="fill blocker"/>
            <View left="10" bottom="10" layout="vertical">
                <Label id="type" module="ui" kerning="0.5" backgroundColor="red">{type}</Label>
                <Label module="ui" id="title" kerning="-0.9">{title}</Label>
                <Label id="date">{date}</Label>
            </View>
        </TableViewRow>
    </TableView>
```

In this example I'm using the collection "news" that was created by my config (which does an API call via the getNews method I've defined) and the transform function I'm using just to remap the model that comes back to the relevant placeholders in the table.

**Comment by jasonkneen** [comment]
and here's how I test it with mock data by having the following in my alloy.js or index.js

``` javascript
var reste = require("reste");

reste.createCollection("news", [{
    headline: "This is a news headline",
    thumbnail: "http://lorempixel.com/640/300/sports/1"
}, {
    headline: "Another news headline, this one stretches to two lines",
    thumbnail: "http://lorempixel.com/640/300/sports/2"
}, {
    headline: "Still more news to go through and read",
    thumbnail: "http://lorempixel.com/640/300/sports/3"
}, {
    headline: "Will the news ever end?",
    thumbnail: "http://lorempixel.com/640/300/sports/4"
}]);
```

and the following in my news.js controller (this is necessary when using createCollection as there is no "fetch" method - so a change trigger is used to bind / re-bind the collection to the UI.

``` javascript
Alloy.Collections.news.trigger("change");
```

**Comment by nuno** [comment]
Thanks @jasonkneen :)

**Comment by awamser** [comment]
I'm doing the same thing here but I get message = "Can't find variable:" for the TableView dataCollection.

**Comment by jasonkneen** [comment]
Show me the xml
