### ISSUE TITLE
Dynamic POST not updating in real-time

### ISSUE THREAD

**Issue by adamtarmstrong** [jasonkneen/RESTe#63]
My vendor provides the API in such a way that I have to change out the POST url depending on the State of residence.

When a method is called, I am trying to use a self executing function on-the-fly.
`post: (function(){ return Ti.App.Properties.getString('apiURL') + 'webapp/agentSearch/'; })(),`

I turned on debug and it appears that RESTe is only evaluating this the very first time the RESTe config is loaded and is not updated/executed each time the method is called.

1. User changes State from 'TX' to 'FL' and I save to Ti.App.Properties

2. User executes a feature in that app that uses a RESTe method.
In my console, I retrieved and logged the saved url property just before calling the RESTe method to ensure the saved value was correct - and it was.
`Ti.API.info("Check server URL, in controller, before executing RESTe: " + Ti.App.Properties.getString('apiURL'));`
**Result: Check server URL, in controller, before executing RESTe: https://fl.amwinsauto.com/osis/**

3. When the RESTe method is executed (with debug enabled), RESTe shows the URL to be:
**::RESTE::https://osis.amwinsauto.com/osis/webapp/agentSearch/**
That is the original URL that was loaded atLaunch (before the user selected their state).

Maybe this is by design, I don't know.  I interpreted the doc to suggest that the post url could be dynamically adjusted in real-time while using the app but my experience suggest it is only dynamically completed upon the initial load of the config.

Is this by design, a bug, or am I doing something incorrect?

Thanks,
Adam.

**Comment by jasonkneen** [comment]
looks like you're self-executing the function which means it'll run once on config and that's that -- so the workaround is to specify the post: as a function and it should be called each time by reste (I think)

**Comment by jasonkneen** [comment]
So I imagine:

```
post: function(){ return Ti.App.Properties.getString('apiURL') + 'webapp/agentSearch/'; },
```

will do it

**Comment by jasonkneen** [comment]
(don't put the () at the end)

**Comment by jasonkneen** [comment]
if that doesn't work (I might not have added it) then adding a beforePost handler to the method will allow you to intercept the arguments before they are sent. reste looks for that and runs this:

```
   beforePost(args.params, function(e) {
                args.params = e;
                send();
            });
```

so it'll fire your handler, passing the args.params -- you can add/replace and do what you want with them, then run the function callback from your handler to continue

**Comment by jasonkneen** [comment]
So you handler would be:

```
beforePost: function(params, callback) {
// do stuff to params
callback(params);
}

**Comment by adamtarmstrong** [comment]
As you suspected, this didnt work (gave me an error "undefined is not a function .....")
`post: function(){ return Ti.App.Properties.getString('apiURL') + 'webapp/agentSearch/'; },`

As for the beforePost....doesnt that just allow me to intercept (and modify) the parameters passed into RESTe?  I don't see how those parameters can be used to overwrite the base url for that method.

**Comment by adamtarmstrong** [comment]
OK, I couldn't quite figure out how to use `beforePost`, but reading back through your doc I realized that `setUrl` did exactly what I needed (in conjunction with overriding the headers in the method).

As always, thanks for your effort on this - Love It!
