### ISSUE TITLE
ES6+?

### ISSUE THREAD

**Issue by chrystoffer** [jasonkneen/RESTe#68]
I have enabled my source to use ES6, but the module is giving error when it finishes compiling
<transpile>true</transpile>

[ERROR] TiExceptionHandler: (main) [420,420] ----- Titanium Javascript Runtime Error -----
[ERROR] TiExceptionHandler: (main) [0,420] - In /reste/reste.js:704,24
[ERROR] TiExceptionHandler: (main) [0,420] - Message: Uncaught TypeError: Cannot set property 'location' of undefined
[ERROR] TiExceptionHandler: (main) [0,420] - Source: module.exports.location={};
[ERROR] V8Exception: Exception occurred at /reste/reste.js:704: Uncaught TypeError: Cannot set property 'location' of undefined

Appcelerator SDK: 7.2.0.GA
Module: 1.5.4

**Comment by jasonkneen** [comment]
sorry, not sure what you mean -- RESTe isn't written in ES6 -- works fine with Alloy projects that use ES6.

**Comment by chrystoffer** [comment]
I just put in my tiapp.xml the flag "transpile = true" and the project did not compile anymore .. giving the error quoted above
Is it necessary to do something else?

**Comment by chrystoffer** [comment]
I changed the file that was installed to the file 'https://github.com/jasonkneen/RESTe/blob/master/reste.js' and it worked normal. thank you

**Comment by jasonkneen** [comment]
Awesome.
