### ISSUE TITLE
Saving a model doesn't work with Appcelerator platform 4.0

### ISSUE THREAD

**Issue by emilioicai** [jasonkneen/RESTe#7]
since updating to the new Appcelerator platform, saving a model is not working because of this piece of code: 

```
Alloy.createModel = function(name, attributes) {
    try {
        return Alloy._createModel(name, attributes);
    } catch (err) {
        return exports.createModel(name, attributes);
    }
}
```

apparently `Alloy._createModel(name, attributes)` crashes (if the model is not defined in Alloy) but the try/catch is not doing its work. Maybe because it's crashing after the Kroll bridge?

The error I'm getting: 

```
[ERROR] The application has crashed with an uncaught exception 'org.test.kroll'.
[ERROR] Reason:
[ERROR] Couldn't find module: alloy/models/Message for architecture: i386
```

**Comment by jasonkneen** [comment]
yeh, will be removing that and just having exports.createModel - unfortunately the try catch is flakey and doesn't always work.

So you should be able to just do

reste.createModel()

instead
