### ISSUE TITLE
Which Backbone versions work with RESTe?

### ISSUE THREAD

**Issue by icecandy** [jasonkneen/RESTe#71]
Just a query, but what versions of Backbone is RESTe designed to work with?
I only ask because use of Backbone in Alloy has a compatibility issue when using Backbone version 1.1.2 where one has to modify the model definition:

extendCollection: function(Collection)
    {
        _.extend(Collection.prototype,
        {
            // extended functions and properties go here

            // For Backbone v1.1.2, uncomment the following to override the
            // fetch method to account for a breaking change in Backbone.
            fetch: function(_options)
            {
                _options = _options ? _.clone(_options) :
                {};
                _options.reset = true;
                return Backbone.Collection.prototype.fetch.call(this, _options);
            },
.........

And specify the version in config.json:

"backbone": "1.1.2"

**Comment by jasonkneen** [comment]
Uses the bultin. Never had to extend a model or collection definition in practice. What’s the reason / need?

-- jason
