### ISSUE TITLE
Error using RESTe with promises

### ISSUE THREAD

**Issue by gildas2k** [jasonkneen/RESTe#74]
Hello @jasonkneen,

I'm currently adding RESTe in my Titanium app and I can't figure out how to use it with promise.
I did the following in my app/lib folder :
npm i reste
npm i q

I have this configuration :
`api.config({
    Q: require('q'),
    debug: true,
    errorsAsObjects: true,
    autoValidateParams: true,
    timeout: 4000,
    url: 'http://localhost:8081/',
    requestHeaders: {
        'Content-Type': 'application/json'
    },
    methods: [{
        name: 'getPing',
        get: 'ping'
    }],
    onError: (e, retry) => {
        console.error(e);
        const dialog = Ti.UI.createAlertDialog({
            title: 'Connection error',
            message: 'There was an error connecting to the server, check your network connection and retry.',
            buttonNames: ['Retry']
        });
        dialog.addEventListener('click', () => {
            retry();
        });
        dialog.show();
    }
});`

I make this call :
`api.getPing()
    .then(result => {
        console.log('result', result);
    });`

And I got this error :
[ERROR] TypeError: api.getPing().then is not a function. (In 'api.getPing().then(function (result) {
[ERROR]   console.log('result', result);
[ERROR] })', 'api.getPing().then' is undefined)

But it works when I make this call :
`api.getPing(result => {
    console.log('result', result);
});`

I'm testing with iOS Simulator (iPhone Xs - 12.2) and using Appc cli 7.0.10, Ti cli 5.1.1 and SDK 8.0.0.GA.

Can you help me ?

Thanks,
Regards,

Gildas.

**Comment by nuborian** [comment]
Same Problem herre - any solution to this? :/

**Comment by jasonkneen** [comment]
@dulmandakh -- are you able to assist?

**Comment by gildas2k** [comment]
> Same Problem herre - any solution to this? :/

My solution was to encapsulate the api call inside a function that return a promise:
```
const myFunc = () => {
    return new Promise((resolve, reject) => {
        api.getPing({}, resolve, (e, retry) => reject({ err: e, retry }));
    });
};
```

**Comment by nuborian** [comment]
Hmm, sure that works. Will try that :)
