### ISSUE TITLE
Collection .fetch with custom POST function?

### ISSUE THREAD

**Issue by nuborian** [jasonkneen/RESTe#75]
Hey, is there an option to use the collections but with a custom function for fetching instead of a get method?

Seems not working, so i hope i am just doing something wrong. :)

**Comment by jasonkneen** [comment]
Not quite sure what you mean but if you're talking about putting your own data into a collection you can do that by just creating an array and using:

`reste.createCollection("collectionname", ARRAY_OF_OBJECTS)` and you'll then be able to access Alloy.Collections.collectionname and use it as normal.
