### ISSUE TITLE
exports.definition for Alloy

### ISSUE THREAD

**Issue by awamser** [jasonkneen/RESTe#8]
This isn't really and issue... but when you're setting up the exports.definition= {} for the Alloy model.  Where are you adding the collection array for the multiple end points? Something like this?

```
exports.definition = {
    config : {
        url: "...",
        models:  [{
            ...
       }],
        methods: [{
            ...
       }]
    }
}
```

Going to test this now...

**Comment by jasonkneen** [comment]
you don't need to use any of the normal models / collections if you use RESTe - it can do all this for you and create the models / collections on the fly without ANY additional files

**Comment by awamser** [comment]
Are you providing a generic config in app/models?

**Comment by jasonkneen** [comment]
You don't need to do anything in app/models. You don't need to define any model or collections files. Reste generates everything on the fly.

**Comment by awamser** [comment]
Ok, I see what you're doing...  Got hung up on the need to create the Alloy Model config file and add:

```
<Collection src="">
```

I believe I have everything setup correctly... but I see an error from the TableView that it can't find the variable for the dataCollection.  Which should be getting created from the the reste.config({}), correct?

**Comment by jasonkneen** [comment]
Don't do the Collection tag - no need for it

You just specify the collection name against the dataCollection attribute - so if it's Alloy.Collections.news then you just specify

``` javascript
 dataCollection="news" 
```

and that's it!

**Comment by jasonkneen** [comment]
See example here

https://github.com/jasonkneen/RESTe/issues/6

**Comment by awamser** [comment]
Thanks for the quick response... That's exactly what I'm doing but still getting the error variable not found.

```

api.config({
    debug : true,
    autoValidateParams : false,
    timeout : 4000,
    url : 'https://api.parse.com/1/',
    requestHeaders : {
        "X-Parse-Application-Id" : Alloy.CFG.parseOptions.applicationID,
        "X-Parse-REST-API-Key" : Alloy.CFG.parseOptions.restKey
    },
    models: [{
        name: "waitTime",
        id: "objectId",
        collections: [{
            name: "waitTimes",
            content: "results",
            read: "getWaitTimes"
        }],
    }],
    methods : [{
        name : "getWaitTimes",
        get : "classes/waitTime"
    }],
    onError : function(e) {
        Ti.API.error(e);
    }
});
```

and then...

index.xml

```
<TableView id="waitTimeTable" dataCollection="waitTimes">
...
</TableView>
```

...also in index.js

```

Alloy.Collections.waitTimes
```

**Comment by jasonkneen** [comment]
Not sure why you have

Alloy.Collections.waitTimes

in index.js?

**Comment by awamser** [comment]
Doh! ...because I can't cut-and-paste.

Using nl.fokkezb.pullToRefresh.

```
function myRefresher(e) {
    Alloy.Collections.waitTimes.fetch({
        success : e.hide,
        error : e.hide
    });
}
```

**Comment by jasonkneen** [comment]
you're doing the config where? in alloy.js? and you don't have any models / collections created using normal Alloy right? So no app/models folder?

**Comment by awamser** [comment]
The reste config is in index.js and i removed the app/models folder.

**Comment by jasonkneen** [comment]
Right,

so it’s most likely that your code isn’t running before the view is executed. Move the config into something that runs before index.js like alloy.js and it’ll work.

The binding is happening before the config is being executed which is why the variable doesn’t exist.
